# Generated by Django 2.2.13 on 2023-11-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20231109_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'SHIRT'), ('HA', 'HAT'), ('HO', 'HOODIE')], max_length=2),
        ),
    ]
