# Generated by Django 2.2.13 on 2023-11-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20231109_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('HA', 'HAT'), ('HO', 'HOODIE'), ('S', 'SHIRT')], max_length=2),
        ),
    ]
