# Generated by Django 2.2.13 on 2023-11-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20231109_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('HA', 'HAT'), ('S', 'SHIRT'), ('HO', 'HOODIE')], max_length=2),
        ),
    ]
