# Generated by Django 2.2.13 on 2024-06-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20240623_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('HO', 'HOODIE'), ('S', 'SHIRT'), ('HA', 'HAT')], max_length=2),
        ),
    ]
