# Generated by Django 2.2.13 on 2023-11-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20231109_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('HO', 'HOODIE'), ('S', 'SHIRT'), ('HA', 'HAT')], max_length=2),
        ),
    ]
