# Generated by Django 2.2.13 on 2024-11-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20241101_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('HA', 'HAT'), ('S', 'SHIRT'), ('HO', 'HOODIE')], max_length=2),
        ),
    ]
