# Generated by Django 2.2.13 on 2024-11-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20241102_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='side',
            field=models.CharField(choices=[('2', 'Back'), ('1', 'Front')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('HO', 'HOODIE'), ('S', 'SHIRT'), ('HA', 'HAT')], max_length=2),
        ),
    ]
