# Generated by Django 5.1.2 on 2024-12-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_item_size_alter_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='size',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(choices=[('2XL', 'Double Extra Lage'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'SHIRT'), ('HO', 'HOODIE'), ('HA', 'HAT')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='side',
            field=models.CharField(choices=[('1', 'Front'), ('2', 'Back')], default='1', max_length=1),
        ),
    ]
