# Generated by Django 5.1.2 on 2024-12-24 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_item_size_orderitem_size_alter_item_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('HO', 'HOODIE'), ('S', 'SHIRT'), ('HA', 'HAT')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='side',
            field=models.CharField(choices=[('2', 'Back'), ('1', 'Front')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('L', 'Large'), ('XL', 'Extra Large'), ('M', 'Medium'), ('2XL', 'Double Extra Lage')], max_length=3),
        ),
    ]
